
export const categoryConstants = {

 ADD_CATEGORY : 'ADD_CATEGORY',
//export const MODIFY_PRODUCT = 'MODIFY_PRODUCT';
 DELETE_CATEGORY : 'DELETE_CATEGORY',
 GET_CATEGORIES : 'GET_CATEGORIES',
 GET_CATEGORY_BY_ID : 'GET_CATEGORY_BY_ID',
}