
export const productConstants = {
  SEARCH_PRODUCTS : 'SEARCH_PRODUCTS',
  ADD_PRODUCT : 'ADD_PRODUCT',
  MODIFY_PRODUCT : 'MODIFY_PRODUCT',
  DELETE_PRODUCT : 'DELETE_PRODUCT',
  GET_PRODUCTS : 'GET_PRODUCTS',
  GET_PRODUCT_BY_ID : 'GET_PRODUCT_BY_ID',
  GET_PRODUCT_BY_CATEGORY : 'GET_PRODUCT_BY_CATEGORY',
  ADD_ITEM_TO_ORDER : 'ADD_ITEM_TO_ORDER',
  DELETE_ITEM_FROM_ORDER : 'DELETE_ITEM_FROM_ORDER',

}